### ISSUE TITLE
Redesign Favorites link

### ISSUE THREAD

**Issue by sagarvxyz** [oslabs-beta/Sveste#117]
The "Favorites" link should be in the header, and change depending on if a user is logged in.

i.e.

User is logged in -> display "Favorites"
User is logged-out -> display "Log-in"

Redesign to meld with our header and general app design.

**Comment by mkizzy** [comment]
117-redesign-favorites-link-1 should be the real branch, dupped branch with wrong setting

**Comment by mkizzy** [comment]
Favorites button and home button are redesigned, add styling and icons
