### ISSUE TITLE
Prevent access to app if user isn't logged in

### ISSUE THREAD

**Issue by sagarvxyz** [oslabs-beta/Sveste#72]
Problem: Users can manually enter a route to bypass login.
Solution: 
- Create an "isLoggedIn" store value that toggles when a user successfully log's in (via a POST fetch request).
- Configure the Svelte SPA Router to require this before serving any application routes other than signup and login.

This is a stop-gap solution for MVP. We'll likely have to reconfigure the entire app to deploy to production in AWS, and can do this differently  then.

**Comment by mkizzy** [comment]
-svelte-spa-router wrap prevents user from going to favorites page if they are not logged in , will redirect to signup instead
-logged in users can access favorites page
